### ISSUE TITLE
problem d'hauteur accueil

### ISSUE THREAD

**Issue by viviannecheung** [ecvwebdesign/ecv-2015-css-snippets#10]
sur chrome 15' mac et 17 'pc problem d'hauteur de fleche et les boutons "demo"et"telecharge" 
sur message envoyer,problem d'hauteur sur le bouton "envoyer"hover
faute d'ortographe sur 'mentions" dans le footer

**Comment by a-ng-d** [comment]
- Problème des boutons résolu.
- Pour la flèche, il vaudrait mieux attendre que toutes les pages soient montées pour que je puisse travailler les styles dans la globalité

**Comment by a-ng-d** [comment]
Problème résolu
