### ISSUE TITLE
[template] sommaire/flèche vers le bas se superposent

### ISSUE THREAD

**Issue by lemelodychan** [ecvwebdesign/ecv-2015-css-snippets#8]
Sur des écrans plus étroits type MBP 15", un sommaire long pousse les liens "démo" et "télécharger" vers le bas et ils se superposent avec la flèche vers le bas
-> faire deux colonnes pour le sommaire ?

**Comment by a-ng-d** [comment]
Problème résolu

Solution : 2 colonnes quand c'est >= 640px et 1 colonne à < 640px
